name: .NET Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build and Pack
      run: |
        dotnet build Material.Icons
        dotnet pack Material.Icons
        dotnet build Material.Icons.WPF
        dotnet pack Material.Icons.WPF
    - name: Publish to Nuget
      run: |
        dotnet nuget push "Material.Icons\bin\Debug\*.nupkg" --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
        dotnet nuget push "Material.Icons.WPF\bin\Debug\*.nupkg" --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish to GitHub Packages
      run: |
        dotnet nuget push "Material.Icons\bin\Debug\*.nupkg" --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/SKProCH/index.json --skip-duplicate
        dotnet nuget push "Material.Icons.WPF\bin\Debug\*.nupkg" --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/SKProCH/index.json --skip-duplicate
